import { StyleSheet, Font } from "@react-pdf/renderer";

// Prevent word hyphenation in @react-pdf/renderer
Font.registerHyphenationCallback((word) => [word]);

export const colors = {
	slate900: "#0f172a",
	slate800: "#1e293b",
	slate700: "#334155",
	slate600: "#475569",
	slate500: "#64748b",
	slate400: "#94a3b8",
	slate300: "#cbd5e1",
	slate200: "#e2e8f0",
	slate100: "#f1f5f9",
	slate50:  "#f8fafc",
	white:    "#ffffff",
	emerald500: "#10b981",
	emerald600: "#059669",
	red500:   "#ef4444",
	indigo500: "#6366f1",
	amber500: "#f59e0b",
} as const;

export const styles = StyleSheet.create({
	page: {
		paddingTop: 50,
		paddingBottom: 65,
		paddingHorizontal: 50,
		fontFamily: "Helvetica",
		fontSize: 10,
		color: colors.slate800,
		backgroundColor: colors.white,
	},
	headerRow: {
		flexDirection: "row",
		justifyContent: "space-between",
		alignItems: "flex-start",
		marginBottom: 12,
	},
	docType: {
		fontSize: 22,
		fontFamily: "Helvetica-Bold",
		color: colors.slate900,
		letterSpacing: 2,
		textTransform: "uppercase",
		marginBottom: 4,
	},
	refLine: {
		fontSize: 8,
		color: colors.slate500,
		letterSpacing: 1.5,
		textTransform: "uppercase",
	},
	dividerThick: {
		width: "100%",
		height: 3,
		backgroundColor: colors.slate900,
		marginBottom: 28,
	},
	labelSmall: {
		fontSize: 7,
		color: colors.slate400,
		textTransform: "uppercase",
		letterSpacing: 2,
		fontFamily: "Helvetica-Bold",
		marginBottom: 5,
	},
	section: {
		marginBottom: 22,
	},
	sectionTitle: {
		fontSize: 8,
		color: colors.slate400,
		textTransform: "uppercase",
		letterSpacing: 1,
		fontFamily: "Helvetica-Bold",
		marginBottom: 10,
	},
	bodyText: {
		fontSize: 10,
		color: colors.slate700,
		lineHeight: 1.6,
	},
	twoCol: {
		flexDirection: "row",
		gap: 24,
	},
	col: { flex: 1 },
	fieldLabel: {
		fontSize: 7,
		color: colors.slate400,
		textTransform: "uppercase",
		letterSpacing: 1.5,
		fontFamily: "Helvetica-Bold",
		marginBottom: 3,
	},
	fieldValue: {
		fontSize: 11,
		fontFamily: "Helvetica-Bold",
		color: colors.slate900,
		marginBottom: 12,
	},
	termRow: {
		flexDirection: "row",
		marginBottom: 8,
	},
	termBadge: {
		width: 16,
		height: 16,
		borderRadius: 8,
		backgroundColor: colors.slate100,
		alignItems: "center",
		justifyContent: "center",
		marginRight: 10,
		marginTop: 1,
	},
	termNumber: {
		fontSize: 7,
		fontFamily: "Helvetica-Bold",
		color: colors.slate500,
	},
	termText: {
		fontSize: 9.5,
		color: colors.slate600,
		lineHeight: 1.55,
		flex: 1,
	},
	signatureRow: {
		flexDirection: "row",
		gap: 40,
		marginTop: 8,
	},
	signatureLine: {
		borderBottomWidth: 1,
		borderBottomColor: colors.slate400,
		marginBottom: 6,
		height: 36,
	},
	footer: {
		position: "absolute",
		bottom: 28,
		left: 50,
		right: 50,
		borderTopWidth: 0.5,
		borderTopColor: colors.slate200,
		paddingTop: 10,
		flexDirection: "row",
		justifyContent: "space-between",
		alignItems: "center",
	},
	footerText: {
		fontSize: 6.5,
		color: colors.slate400,
		textTransform: "uppercase",
		letterSpacing: 2,
		fontFamily: "Helvetica-Bold",
	},
	pageNumber: {
		fontSize: 7,
		color: colors.slate400,
		fontFamily: "Helvetica-Bold",
	},
});
